window.T = {
  ko: {
    lang: 'KOR',
    nav: {
      company: '회사소개',
      business: '사업분야',
      facility: '설비현황',
      esg: '품질·ESG',
      contact: '고객지원',
      companyItems: ['인사말', '경영이념', '연혁', '조직도', '오시는 길'],
      businessItems: ['금형 제작', '사출 생산', '제품 소개', '고객사 현황'],
      facilityItems: ['금형 설비', '사출 설비', '사진/영상'],
      esgItems: ['품질관리 시스템', 'ESG 경영방침', '인증현황'],
    },
    popup: {
      title: '공지사항',
      content: '아이앤테크 홈페이지를 방문해 주셔서 감사합니다.\n신규 홈페이지가 오픈되었습니다. 많은 이용 부탁드립니다.',
      close: '오늘 하루 보지 않기',
      confirm: '확인',
    },
    home: {
      slides: [
        { title: '사출금형의 최적의 솔루션 제안', sub: '축적된 기술력과 생산 노하우를 기반으로\n안정적인 품질 경쟁력을 제공합니다', btn: '사업분야' },
        { title: '설계부터 양산까지\nOne-Stop 생산 시스템', sub: '금형 제작부터 사출 생산까지\n사내 일괄 대응 체계를 구축했습니다', btn: '설비현황' },
        { title: '품질과 납기를 만족시키는\n생산 경쟁력', sub: '고객 요구에 유연하게 대응할 수 있는\n생산 시스템을 운영합니다', btn: '품질관리 시스템' },
      ],
      statsTitle: '아이앤테크의 역량',
      stats: [
        { num: '30+', label: '업력 (년)' },
        { num: '50+', label: '보유 설비 (대)' },
        { num: '3,000+', label: '누적 제작 금형 (개)' },
        { num: '99%', label: '납품 품질 합격률' },
      ],
      aboutTitle: '아이앤테크 소개',
      aboutText: '아이앤테크는 기술보다 먼저 책임감을 생각합니다. 보이지 않는 부분까지 세심하게 검토하고, 더 나은 품질과 안정적인 생산을 위해 끊임없이 연구하며 개선합니다. 이러한 태도가 고객의 신뢰와 오랜 파트너십의 기반이 되고 있습니다.',
      bizTitle: '주요 사업분야',
      bizItems: [
        { title: '사출금형 제작', desc: '자동차 대형 부품용 정밀 사출금형 설계 및 제작' },
        { title: '사출 양산', desc: 'SQ Mark 최상위 등급 품질 관리로 안정적인 사출 양산' },
        { title: '대형 부품 생산', desc: '범퍼 · 크래쉬패드 · 선루프 등 자동차 대형 부품 전문' },
      ],
    },
    ceo: {
      title: '인사말',
      ceoTitle: '기술과 신뢰로 가치를 만드는 제조 파트너',
      ceoName: '아이앤테크㈜ 임직원 일동',
      ceoMsg: '아이앤테크㈜는 자동차 부품 사출금형 제작 및 사출 양산 전문 기업으로, 1992년 법인 설립 이후 30년간 자동차 부품 성형 기술을 바탕으로 설계부터 제작·양산까지 안정적인 생산 시스템을 갖추고 있습니다.\n\n저희는 축적된 기술력과 체계적인 품질 관리를 통해 제품의 완성도를 높이고, 신뢰할 수 있는 제조 파트너로서의 역할을 충실히 수행하고자 노력하고 있습니다.\n\n또한 지속적인 개선 활동과 기술 경쟁력 강화를 통해 품질 혁신을 실현하고, 변화하는 산업 환경 속에서도 고객의 요구에 부합하는 가치를 제공하고자 합니다.\n\n앞으로도 책임 있는 제조와 꾸준한 투자를 통해 고객과 함께 성장하는 기업, 신뢰받는 제조 파트너로 거듭나겠습니다. 관심을 가지고 지켜봐 주십시오.\n\n감사합니다.',
    },
    philosophy: {
      title: '경영이념',
      kicker: 'OUR PHILOSOPHY',
      lead: '고객의 신뢰를 만드는 세 가지 원칙',
      desc: '아이앤테크는 품질 · 기술 · 신뢰라는 세 가지 핵심 원칙을 중심으로, 자동차 부품 제조의 모든 공정에서 일관된 기준으로 운영됩니다.',
      missions: [
        { title: '품질 최우선', en: 'QUALITY FIRST', desc: '설계·제작·양산 전 공정에 최고 수준의 품질 기준을 적용하고, 체계적인 공정 관리를 통해 고객 만족을 실현합니다.' },
        { title: '기술 경쟁력', en: 'TECHNICAL EXCELLENCE', desc: '지속적인 개선 활동과 설비 · 인재에 대한 투자로 기술 경쟁력을 강화하고, 변화하는 산업 환경에서 고객 요구에 부합하는 가치를 제공합니다.' },
        { title: '신뢰받는 파트너', en: 'TRUSTED PARTNER', desc: '책임 있는 제조와 투명한 소통으로 고객과 함께 성장하는 장기 파트너십을 구축합니다.' },
      ],
      pillars: [
        ['ESTABLISHED', '1992'],
        ['EXPERIENCE', '30+ YEARS'],
        ['CORE VALUES', 'QUALITY · TECH · TRUST'],
      ],
    },
    history: {
      title: '연혁',
      items: [
        { year: '2025', events: ['10월 — 공장 증축 (연제동 1069-1, 제2공장)', '03월 — 뿌리기술 및 소부장 기업 인증 취득'] },
        { year: '2024', events: ['04월 — 인도 자동차부품업체 사출금형 수출 시작'] },
        { year: '2023', events: ['06월 — 가족친화기업 인증 취득'] },
        { year: '2019', events: ['06월 — 벤처기업 인증 취득'] },
        { year: '2018', events: ['11월 — 기술혁신형 중소기업 (INNO-BIZ) 인증 취득', '09월 — KS Q ISO 9001:2015 / ISO 9001:2015 인증 취득'] },
        { year: '2017', events: ['03월 — 산학일체형 도제교육 협약', '01월 — 일본 자동차부품업체 사출금형 수출 시작'] },
        { year: '2016', events: ['06월 — 첨단 공장 증축, 하남공장 합병'] },
        { year: '2015', events: ['06월 — 기업부설연구소 금형파트 인정'] },
        { year: '2014', events: ['2014~2015 — 습식 공기청정기 관련 특허증 등록', '01월 — 현대 · 기아차 사출 및 금형부분 SQ Mark "A"등급 취득'] },
        { year: '2013', events: ['03월 — 가두리 양식장용 부구 및 이의 제조방법 특허증 등록', '01월 — 삼성전자 1차 협력업체 선정'] },
        { year: '2012', events: ['01월 — 유망 중소중견 기업 및 고용 우수기업 선정'] },
        { year: '2006', events: ['12월 — KSA 9001:2001 / ISO 9001:2000 인증 취득'] },
        { year: '2002', events: ['02월 — 아이앤테크㈜ 설립, 우성플라스틱 합병'] },
        { year: '1992', events: ['01월 — 우성플라스틱㈜ 설립'] },
      ],
    },
    org: {
      title: '조직도',
      chart: {
        ceo: '대표이사',
        exec: '전무이사',
        qa: '품질관리',
        depts: [
          { name: '금형부', subs: ['설계연구소', 'CNC가공팀', '금형조립팀'] },
          { name: '사출부', subs: ['생산운영팀', '사출생산팀', '조립팀', '출하관리팀'] },
        ],
        support: {
          label: '지원조직',
          en: 'SUPPORT',
          items: ['원가구매', '경영지원'],
        },
        note: '※ 품질관리는 전무이사 직속, 원가구매 · 경영지원은 지원조직',
      },
    },
    location: {
      title: '오시는 길',
      addr: '광주광역시 북구 첨단연신로 398번길 23, 31 (연제동 1069, 1069-1)',
      tel: '062-959-9100',
      fax: '062-954-5332',
      email: 'info@it9100.co.kr',
      directions: [
        { how: '자가용', desc: '호남고속도로 광산 IC → 첨단지구 → 첨단연신로 398번길' },
        { how: '대중교통', desc: '광주송정역 → 첨단지구행 버스 → 첨단연제동 정류장 하차' },
      ],
    },
    mold: {
      title: '금형 제작',
      subtitle: 'Mold Manufacturing',
      intro: '아이앤테크는 CAD/CAM 설계부터 정밀 가공까지 일관 생산 체계를 갖추고, 고객의 요구에 맞는 최적의 금형을 제작합니다.',
      itemsTitle: '주력 양산 아이템',
      itemGroups: [
        { area: '범퍼 시스템', en: 'BUMPER SYSTEM', items: ['FR/RR BUMPER', 'BUMPER COVER', { name: 'GRILLE BUMPER', src: 'assets/mold-grille-bumper.jpg' }] },
        { area: '선루프 시스템', en: 'SUNROOF SYSTEM', items: [{ name: 'FRONT GLASS', src: 'assets/mold-sunroof-front.jpg' }, { name: 'MOVABLE GLASS', src: 'assets/mold-sunroof-mov.jpg' }, { name: 'REAR GLASS', src: 'assets/mold-sunroof-rear.jpg' }] },
        { area: '램프 시스템', en: 'LAMP SYSTEM', items: [{ name: 'LAMP COVER', src: 'assets/mold-lamp-cover.jpg' }] },
        { area: '외장 트림', en: 'EXTERIOR TRIM', items: [{ name: 'FENDER GARNISH', src: 'assets/mold-fender-garnish.jpg' }, { name: 'DOOR GARNISH', src: 'assets/mold-door-garnish.jpg' }, { name: 'DOOR GARNISH', src: 'assets/mold-rear-door-garnish.jpg' }, { name: 'UNDER COVER', src: 'assets/mold-under-cover.jpg' }] },
        { area: '내장 트림', en: 'INTERIOR TRIM', items: [{ name: 'CRASH PAD', src: 'assets/mold-crashpad.jpg' }, { name: 'CONSOLE', src: 'assets/mold-console.jpg' }, { name: 'LUGGAGE TRIM', src: 'assets/mold-luggage.jpg' }, { name: 'PILLAR TRIM', src: 'assets/mold-pillar-trim.jpg' }] },
        { area: '공조 시스템', en: 'HVAC SYSTEM', items: ['AIR DUCT', 'HVAC DUCT'] },
        { area: '전장 부품', en: 'ELECTRICAL PARTS', items: ['MODULE HOUSING'] },
        { area: 'EV · 친환경차 부품', en: 'EV · ECO PARTS', items: [{ name: 'CHARGING INLET', src: 'assets/mold-charging-inlet.jpg' }, { name: 'EV CHARGER HOUSING', src: 'assets/mold-charger-housing.jpg' }, { name: 'HYDROGEN DOME', src: 'assets/mold-h2-dome.jpg' }, { name: 'HYDROGEN LINER', src: 'assets/mold-h2-liner.jpg' }] },
      ],
      items: [
        { title: 'F/R BUMPER MOLD', cat: 'EXTERIOR', desc: '자동차 전·후방 범퍼용 대형 사출금형' },
        { title: 'CRASH PAD (I/P) MOLD', cat: 'INTERIOR', desc: '운전석 인스트루먼트 패널 사출금형' },
        { title: 'SUNROOF PU FRAME MOLD', cat: 'EXTERIOR', desc: '선루프 PU 프레임 인서트 사출금형' },
        { title: 'SIDE SILL GARNISH MOLD', cat: 'EXTERIOR', desc: '차체 록커(사이드 실) 가니쉬 사출금형' },
        { title: 'LUGGAGE SIDE TRIM MOLD', cat: 'INTERIOR', desc: '러기지룸 사이드 트림 사출금형' },
        { title: 'H2 LINER MOLD', cat: 'ECO', desc: 'Type 4 수소저장용기 Liner 사출금형' },
      ],
      process: ['수주 및 제품 검토', '금형 설계 (2D · 3D)', 'CNC 정밀 가공', '방전 · 와이어 가공', '조립 및 사상', '시사출(T/O) 및 품질 확인', '납품 및 양산 대응'],
    },
    injection: {
      title: '사출 생산',
      subtitle: 'Injection Production',
      intro: '아이앤테크 사출부는 원재료 입고부터 출하까지 8단계 표준 공정을 운영합니다.\n각 단계마다 자동차 부품 제작 관리 기준에 맞춘 검사·기록 관리로 품질과 납기를 동시에 만족시킵니다.',
      processDetail: [
        { title: '원재료 입고\n수입검사', bullets: ['M/SHEET', '자재수불대장 · M/SHEET 접수', '선입선출 및 LOT별 식별관리'] },
        { title: '부자재 검사', bullets: ['수입검사'] },
        { title: '사출', bullets: ['사출성형 (육안 · 계측판)', '중량 · 성형 · 저울 확인', '온도 및 기록관리'] },
        { title: '조립', bullets: ['육안 · 전수 · 작업표준 · 작업일지', '이탈 및 누락 없을 것', '불량 발생 시 격리 및 분쇄'] },
        { title: '완제품 검사', bullets: ['출하검사', '육안 · 전수 · 출하검사 기준서', '거친표면 · 수축 등 없을 것', '불량 발생 시 격리 및 분쇄'] },
        { title: '포장 · 보관', bullets: ['포장상태 양호할 것', '육안 · 전수 · 작업일지', '식별표 부착 · 품번 · 수량', '사양확인 / 출하대장'] },
        { title: '정기검사', bullets: ['유해물질', '성적서 1회 / 6개월'] },
        { title: '출하', bullets: [] },
      ],
      specs: [
        { label: '사출기 보유 대수', value: '15대' },
        { label: '최대 형체력', value: '3,000T' },
        { label: '주요 톤수 범위', value: '180T ~ 3000T' },
        { label: '생산 동', value: 'A동 (중소형)\nB동 (대형 전용)' },
      ],
      items: [
        { title: '일반 사출', desc: '다양한 소재의 플라스틱 부품 양산' },
        { title: '인서트 사출', desc: '금속 인서트 포함 복합 부품 생산' },
        { title: '이중 사출', desc: '2가지 소재/색상 동시 성형' },
        { title: '초정밀 사출', desc: '±0.01mm 공차의 정밀 부품 생산' },
        { title: '수소 라이너 사출', desc: '수소탱크용 고압 라이너 정밀 사출 성형' },
      ],
      capabilitiesIntro: '자동차 내·외장 부품 양산을 위한 다양한 사출 기술 대응',
      coreTech: [
        { title: '일반 사출성형', desc: '자동차 내·외장 부품 양산' },
        { title: '대형 사출', desc: '3000T급 대형 사출 대응' },
        { title: '인서트 사출', desc: '금속 인서트 일체 성형' },
        { title: '정밀 사출', desc: '고정밀 치수 및 품질 관리' },
      ],
      materials: {
        title: '소재 대응 역량',
        groups: [
          { name: '범용 엔지니어링 소재', items: ['PP', 'ABS', 'PC/ABS', 'PA6'] },
          { name: '기능성 소재', items: ['GF 강화재', '난연재', '고내열 소재'] },
          { name: '친환경 소재', items: ['경량화 소재', '친환경 소재', '재활용 소재'] },
        ],
      },
      production: {
        title: '생산 대응 역량',
        bullets: [
          '170T ~ 3000T 사출설비 보유',
          '금형 ~ 시사출 ~ 양산 일괄 대응',
          '자동화 생산 및 품질관리 시스템',
          '현대·기아 SQ 기반 생산체계 구축',
        ],
      },
    },
    products: {
      title: '제품 소개',
      subtitle: 'Products',
      intro: '아이앤테크는 자동차 내·외장 전 영역에 걸쳐 다양한 부품을 양산하고 있습니다.',
      categories: ['전체', '자동차 부품', '기계장비용', '기타'],
      items: [
        { name: '도어 트림', cat: '자동차 부품', desc: '자동차 도어 내장재 플라스틱 부품' },
        { name: '범퍼 부품', cat: '자동차 부품', desc: '전/후방 범퍼 어셈블리 부품' },
        { name: '인스트루먼트 패널', cat: '자동차 부품', desc: '대시보드 플라스틱 구조물' },
        { name: '콘솔 박스', cat: '자동차 부품', desc: '센터 콘솔 및 수납 부품' },
        { name: '기어 커버', cat: '기계장비용', desc: '산업용 기계 커버 부품' },
        { name: '하우징 케이스', cat: '기계장비용', desc: '전장부품 하우징 케이스' },
        { name: '클립/패스너', cat: '기타', desc: '각종 고정용 클립 및 패스너' },
        { name: '특수 부품', cat: '기타', desc: '고객 주문형 특수 플라스틱 부품' },
      ],
    },
    clients: {
      title: '고객사 현황',
      subtitle: 'Clients &amp; Coverage',
      intro: '아이앤테크는 자동차 부품 산업을 중심으로 국내외 완성차·1차 협력사 및 다양한 산업군에 사출금형과 사출 제품을 공급해왔습니다.\n고객사별 요구사항과 제품 특성을 분석하여 맞춤형 제작 및 안정적인 품질 대응에 힘써왔으며,\n지속적인 해외 바이어 발굴과 공급 분야 확대를 통해 산업과 지역을 넓혀가고 있습니다.\n이러한 공급 경험과 대응 역량은 아이앤테크의 신뢰와 경쟁력을 보여주는 기반입니다.',
      statsTitle: '공급 이력',
      statsSub: 'Supply Track Record',
      stats: [
        { num: '30+', label: '업력', sub: 'Years in Business' },
        { num: '4', label: '진출 국가', sub: 'Countries Served' },
        { num: '15+', label: '연 신규 양산 아이템', sub: 'New Items / Year' },
      ],
      industriesTitle: '대응 산업군',
      industriesSub: 'Industries We Serve',
      industries: [
        { name: '자동차 부품 외장·내장재', cat: 'AUTOMOTIVE EXT · INT', desc: '러기지 트림, 범퍼 등 자동차 대형 외장/내장 부품' },
        { name: '선루프 금형', cat: 'SUNROOF MOLDS', desc: '일반 선루프, 파노라마 선루프 금형 제작' },
        { name: '전자 · 가전', cat: 'ELECTRONICS', desc: '대형 가전 외장 및 정밀 기구 부품' },
      ],
      regionsTitle: '지역 대응 범위',
      regionsSub: 'Sourcing Reach',
      regionsDesc: '본사(광주)를 거점으로 국내 전 지역 및 일본·중국·인도에 사출금형과 사출 제품을 직접 공급합니다.',
      regions: [
        { code: 'KR', flag: '🇰🇷', name: '대한민국', role: '본사', desc: '광주 · 전북 · 화성 · 울산 · 경남 등 국내 전 지역', since: '1992', primary: true },
        { code: 'JP', flag: '🇯🇵', name: '일본', role: '금형 수출', desc: '자동차 부품업체 사출금형 공급', since: '2013', primary: false },
        { code: 'CN', flag: '🇨🇳', name: '중국', role: '금형 수출', desc: '자동차 부품업체 사출금형 공급', since: '2014', primary: false },
        { code: 'IN', flag: '🇮🇳', name: '인도', role: '금형 수출', desc: '자동차 부품업체 사출금형 공급', since: '2020', primary: false },
      ],
      globalTitle: '글로벌 경험',
      globalSub: 'Global Track Record',
      globalDesc: '국내를 넘어 일본·중국·인도 등 해외 자동차 부품 시장에 사출금형을 공급하며,\n완성차 OEM 품질 기준에 부합하는 제조 역량을 입증해왔습니다.',
      timeline: [
        { year: '2020', event: '인도 자동차부품업체 사출금형 수출 시작' },
        { year: '2014', event: '일본 · 중국 자동차부품업체 사출금형 수출 확대' },
        { year: '2013', event: '일본 자동차부품업체 사출금형 수출 시작' },
      ],
    },
    moldFacility: {
      title: '금형 설비',
      subtitle: 'Mold Facilities',
      intro: '최첨단 CNC 가공 설비와 정밀 방전·계측 장비를 보유하여 고정밀 대형 금형을 제작합니다.',
      groups: [
        {
          name: 'CNC\nMachine',
          en: 'CNC MACHINE',
          specHead: 'TABLE SIZE',
          showLoad: true,
          rows: [
            { model: 'SIRIUS - 1750S', spec: '3,000 × 1,750', load: '—', qty: 1 },
            { model: 'SIRIUS - 1250S', spec: '2,150 × 850', load: '—', qty: 1 },
            { model: 'SIRIUS - 1050 8K', spec: '2,500 × 850', load: '—', qty: 1 },
            { model: 'SIRIUS - 850 S', spec: '2,150 × 850', load: '—', qty: 3 },
            { model: 'SIRIUS - 650 S', spec: '1,800 × 650', load: '—', qty: 1 },
            { model: 'SIRIUS - UL+20K', spec: '1,600 × 700', load: '—', qty: 1 },
            { model: 'SIRIUS - 7040 10K', spec: '1,600 × 700', load: '—', qty: 2 },
            { model: 'SIRIUS - 550(UL)', spec: '1,300 × 550', load: '—', qty: 2 },
          ],
        },
        {
          name: 'EDM\nMachine',
          en: 'EDM MACHINE',
          rows: [
            { model: 'UNI - 430', spec: '700 × 360', qty: 1 },
            { model: 'UNI - 500', spec: '700 × 462', qty: 1 },
            { model: 'MAKINO 106', spec: '1,300 × 950', qty: 1 },
            { model: 'MAKINO 156', spec: '2,000 × 1,000', qty: 1 },
          ],
        },
        {
          name: 'Other\nMachine',
          en: 'OTHER MACHINE',
          rows: [
            { model: '다이스포팅기', spec: '—', qty: '—' },
            { model: '금형반전기', spec: '—', qty: '—' },
            { model: '호이스트 (크레인)', spec: '—', qty: '—' },
          ],
        },
      ],
    },
    injFacility: {
      title: '사출 설비',
      subtitle: 'Injection Molding Facilities',
      kicker: 'INJECTION CAPABILITY',
      hero: {
        eyebrow: '170T — 3,000T',
        headline: '170T부터 3,000T까지,\n소형 내장재부터 대형 외장재까지',
        desc: '아이앤테크 사출부는 대형 사출동(B동)과 다품종 대응 A동으로 구성되어, 다양한 사이즈의 외장재 및 내장재, 자동차 전 부품군을 안정적으로 양산합니다.',
      },
      stats: [
        { v: '15', u: '대', l: '총 사출기 보유', e: 'TOTAL MACHINES' },
        { v: '3,000', u: 'T', l: '최대 형체력', e: 'MAX CLAMPING' },
        { v: '2', u: '개동', l: '전용 생산동', e: 'PLANTS' },
        { v: '24/7', u: '', l: '양산 운영체계', e: 'OPERATION' },
      ],
      plantB: {
        tag: 'PLANT B · LARGE SIZE',
        title: '사출 B동 · 대형 사출 전용',
        sub: 'Injection Plant B — Large Size',
        desc: '범퍼, 수소 라이너 탱크 등 자동차 외장재, 내장재 대형 부품 전용 생산동.\n2,100T 이상 대형 사출기 4대를 운영하며, 신공장 기반의 자동화 라인으로 대형 부품 안정 양산 체계를 갖추고 있습니다.',
        machines: [
          { ton: 3000, qty: 1 },
          { ton: 2500, qty: 1 },
          { ton: 2200, qty: 1 },
          { ton: 2100, qty: 1 },
        ],
        totalLabel: '총 4대',
      },
      plantA: {
        tag: 'PLANT A · MID & SMALL',
        title: '사출 A동 · 중소형 다품종 대응',
        sub: 'Injection Plant A — Mid & Small Size',
        desc: '중소형 자동차 부품 다품종 양산 대응 라인.\n180T부터 2,200T까지 폭넓은 톤수의 사출기를 운영하여 다양한 부품 사양에 유연하게 대응합니다.',
        machines: [
          { ton: 2200, qty: 1 },
          { ton: 2000, qty: 1 },
          { ton: 1400, qty: 1 },
          { ton: 1300, qty: 1 },
          { ton: 850, qty: 1 },
          { ton: 650, qty: 1 },
          { ton: 550, qty: 2 },
          { ton: 380, qty: 1 },
          { ton: 300, qty: 1 },
          { ton: 180, qty: 1 },
        ],
        totalLabel: '총 11대',
      },
      capability: {
        tag: 'PRODUCTION CAPABILITY',
        title: '자동차 부품 양산 Capability',
        desc: '단순 설비 보유를 넘어, 자동차 전 부품군에 대응하는 양산 체계를 운영합니다.',
        items: [
          { ko: '자동차 내장 부품', en: 'Automotive Interior Parts' },
          { ko: '자동차 외장 부품', en: 'Automotive Exterior Parts' },
          { ko: '대형 범퍼 성형', en: 'Large-size Bumper Molding' },
          { ko: '선루프 부품', en: 'Sunroof Components' },
          { ko: '러기지 트림', en: 'Luggage Trim' },
          { ko: '인서트 사출', en: 'Insert Molding' },
          { ko: '양산 시스템 운영', en: 'Mass Production System' },
        ],
      },
    },
    factory: {
      title: '사진/영상',
      subtitle: 'Factory Gallery',
      intro: '아이앤테크의 최신 생산 설비와 공장 내부를 확인하세요.',
      areas: ['금형 제작동', '사출 생산동', '공장 외부 전경', 'VIDEO'],
      videos: [
        // 유튜브 링크 주시면 채웁니다. 형식: { title: '제목', youtube: 'https://youtu.be/VIDEO_ID' }
        // { title: '아이앤테크 회사 소개 영상', youtube: '' },
      ],
      galleries: {
        '금형 제작동': [
          { src: 'assets/mold-gallery-2.jpg', cap: '대형 금형동 · 화천 25호기 그릴 범퍼 가공' },
          { src: 'assets/mold-gallery-1.jpg', cap: '5축 가공기 · 90° 가공 중' },
          { src: 'assets/mold-gallery-3.jpg', cap: '5축 가공기 · 45° 가공 중' },
          { src: 'assets/mold-gallery-4.jpg', cap: '화천 12호기 가공 중' },
          { src: 'assets/mold-gallery-5.jpg', cap: '투헤드 방전기 방전 중' },
          { src: 'assets/mold-gallery-8.jpg', cap: '다이스포팅기 500톤' },
          { src: 'assets/mold-gallery-7.jpg', cap: '기존 가공동 전경' },
          { src: 'assets/mold-gallery-6.jpg', cap: '기존 사상동 전경' },
          { src: 'assets/mold-gallery-9.jpg', cap: '메인판넬 크러시패드 가공 중' },
        ],
        '사출 생산동': [
          { src: 'assets/inj-gallery-1.jpg', cap: '대형 사출동 전경' },
          { src: 'assets/inj-gallery-2.jpg', cap: '대형 사출동 · 사출 라인' },
          { src: 'assets/inj-gallery-6.jpg', cap: '대형 사출동 · 금형 교환장치' },
          { src: 'assets/inj-gallery-5.jpg', cap: '대형 사출동 · 오토피딩 연결' },
          { src: 'assets/inj-gallery-3.jpg', cap: '기존 사출동 전경' },
          { src: 'assets/inj-gallery-4.jpg', cap: '기존 조립동 전경' },
        ],
        '공장 외부 전경': [
          { src: 'assets/ext-gallery-1.jpg', cap: '신공장 좌측 전경' },
          { src: 'assets/ext-gallery-2.jpg', cap: '회사 전경 (드론)' },
          { src: 'assets/ext-gallery-3.jpg', cap: '회사 전경 (드론)' },
          { src: 'assets/ext-gallery-4.jpg', cap: '기존 사출동 전경 (드론)' },
        ],
      },
    },
    quality: {
      title: '품질관리 시스템',
      subtitle: 'Quality Management System',
      intro: '아이앤테크는 SQ Mark 최상위 등급 인증을 바탕으로, 금형 제작부터 사출 양산·검사·출하에 이르는 전 공정을 사내에서 일괄 관리합니다.\n축적된 기술력과 표준화된 프로세스로 고객이 요구하는 품질과 납기를 동시에 만족시킵니다.',
      sqTitle: 'SQ Mark 최상위 등급 취득',
      sqDesc: '현대·기아 완성차 기준에 부합하는 사출 및 사출금형 부문 최상위 등급을 보유하고 있습니다. 부품 협력사의 품질·납기·기술 역량을 종합 평가하는 SQ 인증 체계의 최고등급은 OEM 직납 수준의 신뢰를 의미합니다.',
      pillars: [
        {
          num: '01', title: '품질 대응 체계', sub: 'Quality Response',
          items: ['SQ Mark 최상위 등급 기준 운영', '고객 품질 기준 대응', '양산 품질 관리 프로세스'],
        },
        {
          num: '02', title: '생산 관리', sub: 'Production Control',
          items: ['금형~사출 공정 통합 관리', '공정별 품질 점검', '생산 이력 관리·추적'],
        },
        {
          num: '03', title: '검사 시스템', sub: 'Inspection System',
          items: ['초품(初品) 검사', '공정 중 검사', '출하 검사'],
        },
        {
          num: '04', title: '고객 대응', sub: 'Customer Response',
          items: ['고객 요구사항 반영', '신속한 문제 대응', '지속적인 품질 개선'],
        },
      ],
      flowTitle: '품질 관리 공정 흐름',
      flowSub: '입고에서 출하까지, 각 공정마다 검증을 거쳐 품질을 보증합니다.',
      flow: [
        ['수입검사', '원자재 · 부품'],
        ['초품검사', '신규 양산 1차 승인'],
        ['공정검사', '사출 중 자주검사'],
        ['최종검사', '치수 · 외관 · 기능'],
        ['출하검사', '포장 · 식별 · 적재'],
      ],
      galleryTitle: '품질 관리 현장',
      gallery: [
        { label: '품질 회의', desc: '주간 품질 회의 및 개선 활동' },
        { label: '측정실', desc: 'CMM 정밀 측정실' },
        { label: '검사 장비', desc: '3D 측정기 · 게이지' },
        { label: '사출 생산 현장', desc: '실시간 품질 모니터링' },
      ],
    },
    esg: {
      title: 'ESG 경영방침',
      subtitle: 'ESG Management',
      intro: '아이앤테크는 환경(E), 사회(S), 지배구조(G)의 세 가지 축을 중심으로 지속가능한 경영을 실현합니다.',
      certTitle: '인증 현황',
      certDesc: '아이앤테크는 국제 표준 및 국가 인증 체계에 부합하는 기술력과 경영 시스템을 갖추고 있습니다.',
      certs: [
        { code: 'INNO-BIZ', name: '기술혁신형 중소기업', body: '중소벤처기업부', period: '2024.12.10 ~ 2027.12.09', file: 'assets/cert-innobiz.jpg', type: 'img', color: '#0d2045' },
        { code: 'VENTURE', name: '벤처기업 확인', body: '벤처기업확인기관', period: '2025.04.29 ~ 2028.04.28', file: 'assets/cert-venture.jpg', type: 'img', color: '#15305f' },
        { code: 'ROOT', name: '뿌리기업 확인', body: '한국생산기술연구원', period: '2023.04.13 ~ 2026.04.12', file: 'assets/cert-ppuri.jpg', type: 'img', color: '#15305f' },
        { code: '소부장', name: '소재·부품·장비 전문기업', body: '한국산업기술기획평가원', period: '2025.06.27 ~ 2028.06.26', file: 'assets/cert-sobujang.jpg', type: 'img', color: '#15305f' },
        { code: 'SQ', name: 'SQ 인증 (사출)', body: '현대자동차·기아', period: '~ 2025.06.30', file: 'assets/cert-sq-injection.jpg', type: 'img', color: '#b07d0a' },
        { code: 'SQ', name: 'SQ 인증 (사출금형)', body: '현대자동차·기아', period: '~ 2025.06.30', file: 'assets/cert-sq-mold.jpg', type: 'img', color: '#b07d0a' },
        { code: 'PATENT', name: '특허 · 가두리양식장용 부구', body: '특허청 · 제10-1247751호', period: '2013.03.20 등록', file: 'assets/cert-patent.jpg', type: 'img', color: '#15305f' },
        { code: 'ISO 9001', name: '품질경영시스템', body: 'KMR 한국경영인증원', period: '2024.12.22 ~ 2027.12.21', file: 'assets/cert-iso9001.jpg', type: 'img', color: '#0d2045' },
        { code: 'ISO 14001', name: '환경경영시스템', body: '', period: '', file: null, type: 'pending', color: '#2e7d52' },
        { code: 'KOSHA-MS', name: '안전보건경영시스템', body: '', period: '', file: null, type: 'pending', color: '#8b2500' },
        { code: 'FAMILY', name: '가족친화기업', body: '', period: '', file: null, type: 'pending', color: '#15305f' },
      ],
      pillars: [
        {
          key: 'E', label: '환경 (Environmental)', color: '#2e7d52',
          items: ['온실가스 배출량 감축 목표 수립 및 이행', '에너지 효율 개선 및 재생에너지 도입', '폐기물 재활용률 향상', '친환경 원부자재 우선 사용'],
        },
        {
          key: 'S', label: '사회 (Social)', color: '#1a56a0',
          items: ['임직원 안전보건 관리 강화', '공정한 채용 및 다양성 존중', '협력사와의 상생 협력', '지역사회 공헌 활동 참여'],
        },
        {
          key: 'G', label: '지배구조 (Governance)', color: '#5a3a8c',
          items: ['투명한 경영 정보 공시', '윤리경영 실천 및 부패방지', '이사회 독립성 강화', '주주 및 이해관계자 소통 강화'],
        },
      ],
    },
    contact: {
      title: '문의하기',
      subtitle: 'Contact Us',
      intro: '제품 및 서비스에 관한 문의사항을 남겨주시면 빠른 시일 내에 답변 드리겠습니다.',
      fields: { name: '성명', company: '회사명', tel: '연락처', email: '이메일', subject: '문의 제목', message: '문의 내용', agree: '개인정보 수집 및 이용에 동의합니다.', submit: '문의 접수', required: '필수 항목을 모두 입력해주세요.', success: '문의가 접수되었습니다. 빠른 시일 내 답변 드리겠습니다.' },
      info: { addr: '광주광역시 북구 첨단연신로 398번길 23, 31 (연제동 1069, 1069-1)', tel: '062-959-9100', fax: '062-954-5332', email: 'info@it9100.co.kr', hours: '평일 09:00 ~ 18:00 (주말/공휴일 휴무)' },
    },
    footer: {
      company: '아이앤테크',
      biz: '사업자등록번호: 410-81-69700',
      addr: '광주광역시 북구 첨단연신로 398번길 23, 31',
      tel: 'TEL: 062-959-9100',
      fax: 'FAX: 062-954-5332',
      email: 'EMAIL: info@it9100.co.kr',
      copy: '© 2024 I&TECH Co., Ltd. All Rights Reserved.',
      privacy: '개인정보처리방침',
    },
  },

  en: {
    lang: 'ENG',
    nav: {
      company: 'About Us',
      business: 'Business',
      facility: 'Facilities',
      esg: 'Quality · ESG',
      contact: 'Contact',
      companyItems: ['CEO Greeting', 'Philosophy', 'History', 'Organization', 'Location'],
      businessItems: ['Mold Manufacturing', 'Injection Production', 'Products', 'Clients'],
      facilityItems: ['Mold Facilities', 'Injection Facilities', 'Factory Gallery'],
      esgItems: ['Quality System', 'ESG Management', 'Certifications'],
    },
    popup: {
      title: 'Notice',
      content: 'Thank you for visiting I&TECH.\nOur new website has been launched. We appreciate your interest.',
      close: 'Do not show today',
      confirm: 'Close',
    },
    home: {
      slides: [
        { title: 'Optimal Solutions for\nInjection Molds', sub: 'Built on accumulated technology and production know-how,\nwe deliver stable, competitive quality.', btn: 'Our Business' },
        { title: 'One-Stop Production:\nDesign to Mass Output', sub: 'From mold fabrication through injection production,\nan integrated in-house response system.', btn: 'Facilities' },
        { title: 'Production Capability\nMeeting Quality & Lead Time', sub: 'A production system that responds flexibly\nto every customer requirement.', btn: 'Quality System' },
      ],
      statsTitle: 'I&TECH in Numbers',
      stats: [
        { num: '30+', label: 'Years in Business' },
        { num: '50+', label: 'Machines' },
        { num: '3,000+', label: 'Molds Produced' },
        { num: '99%', label: 'Quality Pass Rate' },
      ],
      aboutTitle: 'About I&TECH',
      aboutText: 'I&TECH manufactures injection molds and runs injection mass production for large automotive parts — both within a single facility. Our integrated workflow from mold design and fabrication through to mass production, together with Hyundai · Kia SQ Mark A grade in both injection and mold divisions, supports stable production of large body parts.',
      bizTitle: 'Core Business Areas',
      bizItems: [
        { title: 'Mold Manufacturing', desc: 'Precision injection mold design and fabrication for large automotive parts' },
        { title: 'Injection Production', desc: 'Stable mass production under SQ Mark top-grade quality management' },
        { title: 'Large Body Parts', desc: 'Specialists in bumpers, crash pads, sunroofs and other large parts' },
      ],
    },
    ceo: {
      title: 'CEO Greeting',
      ceoTitle: 'A Manufacturing Partner Building Value Through Technology and Trust',
      ceoName: 'I&TECH Co., Ltd. — All Employees',
      ceoMsg: 'I&TECH Co., Ltd. is a specialist in injection mold manufacturing and injection production for automotive parts. Since our incorporation in 1992, we have built a stable production system covering design, fabrication, and mass production based on more than 30 years of expertise in molding automotive components.\n\nThrough accumulated technical capability and a systematic quality management framework, we strive to elevate the completeness of every product and to faithfully fulfill our role as a reliable manufacturing partner.\n\nWe pursue quality innovation through continuous improvement and the strengthening of our technical competitiveness, and we aim to deliver value that meets our customers’ needs even amid a rapidly changing industrial environment.\n\nThrough responsible manufacturing and sustained investment, we will continue to grow alongside our customers and reaffirm our standing as a trusted manufacturing partner.\n\nThank you.',
    },
    philosophy: {
      title: 'Management Philosophy',
      kicker: 'OUR PHILOSOPHY',
      lead: 'Three principles that build customer trust',
      desc: 'I&TECH operates under three core principles — Quality, Technology, and Trust — applied as a consistent standard across every stage of automotive parts manufacturing.',
      missions: [
        { title: 'Quality First', en: 'QUALITY FIRST', desc: 'We apply the highest quality standards across design, fabrication, and mass production, achieving customer satisfaction through systematic process control.' },
        { title: 'Technical Excellence', en: 'TECHNICAL EXCELLENCE', desc: 'We strengthen our technical competitiveness through continuous improvement and investment in equipment and people, delivering value aligned with evolving customer needs.' },
        { title: 'Trusted Partner', en: 'TRUSTED PARTNER', desc: 'Through responsible manufacturing and transparent communication, we build long-term partnerships and grow alongside our customers.' },
      ],
      pillars: [
        ['ESTABLISHED', '1992'],
        ['EXPERIENCE', '30+ YEARS'],
        ['CORE VALUES', 'QUALITY · TECH · TRUST'],
      ],
    },
    history: {
      title: 'History',
      items: [
        { year: '2025', events: ['Oct — Factory expansion (Yeonje-dong 1069-1, 2nd factory)', 'Mar — Certified as Root-Industry & Materials/Components/Equipment company'] },
        { year: '2024', events: ['Apr — Began exporting injection molds to automotive parts maker in India'] },
        { year: '2023', events: ['Jun — Family-Friendly Company certification'] },
        { year: '2019', events: ['Jun — Venture Company certification'] },
        { year: '2018', events: ['Nov — INNO-BIZ certification', 'Sep — KS Q ISO 9001:2015 / ISO 9001:2015 certification'] },
        { year: '2017', events: ['Mar — Industry-Academia Apprenticeship Agreement', 'Jan — Began exporting injection molds to automotive parts maker in Japan'] },
        { year: '2016', events: ['Jun — Advanced factory expansion; merger with Hanam factory'] },
        { year: '2015', events: ['Jun — Corporate R&D center (mold division) accredited'] },
        { year: '2014', events: ['2014–2015 — Patents registered for wet air purifier', 'Jan — Hyundai · Kia SQ Mark "A" grade in injection & mold divisions'] },
        { year: '2013', events: ['Mar — Patent registered for fish-cage buoy and manufacturing method', 'Jan — Selected as Tier-1 supplier to Samsung Electronics'] },
        { year: '2012', events: ['Jan — Selected as a Promising SME & Outstanding Employer'] },
        { year: '2006', events: ['Dec — KSA 9001:2001 / ISO 9001:2000 certification'] },
        { year: '2002', events: ['Feb — I&TECH Co., Ltd. established; merger with Woosung Plastic'] },
        { year: '1992', events: ['Jan — Woosung Plastic Co., Ltd. founded'] },
      ],
    },
    org: {
      title: 'Organization',
      chart: {
        ceo: 'CEO',
        exec: 'Executive Director',
        qa: 'Quality Control',
        depts: [
          { name: 'Mold Division', subs: ['Design R&D', 'CNC Processing', 'Mold Assembly'] },
          { name: 'Injection Division', subs: ['Production Ops', 'Injection', 'Assembly', 'Shipping'] },
        ],
        support: {
          label: 'Support',
          en: 'SUPPORT',
          items: ['Procurement', 'Management Support'],
        },
        note: '※ Quality Control reports directly to the Executive Director. Procurement & Management Support are support functions.',
      },
    },
    location: {
      title: 'Location',
      addr: '23, 31, Cheomdanyeonsin-ro 398beon-gil, Buk-gu, Gwangju, Korea',
      tel: '062-959-9100',
      fax: '062-954-5332',
      email: 'info@it9100.co.kr',
      directions: [
        { how: 'By Car', desc: 'Honam Expressway Gwangsan IC → Cheomdan District → Cheomdanyeonsin-ro 398beon-gil' },
        { how: 'By Transit', desc: 'Gwangju-Songjeong Station → Bus to Cheomdan District → Yeonje-dong Stop' },
      ],
    },
    mold: {
      title: 'Mold Manufacturing',
      subtitle: 'Mold Manufacturing',
      intro: 'I&TECH operates an integrated production system from CAD/CAM design to precision machining, delivering optimal molds tailored to customer requirements.',
      itemsTitle: 'Key Production Items',
      itemGroups: [
        { area: 'Bumper System', en: 'BUMPER SYSTEM', items: ['FR/RR BUMPER', 'BUMPER COVER'] },
        { area: 'Sunroof System', en: 'SUNROOF SYSTEM', items: ['FRONT GLASS', 'MOVABLE GLASS', 'REAR GLASS'] },
        { area: 'Lamp System', en: 'LAMP SYSTEM', items: ['FOG LAMP COVER'] },
        { area: 'Exterior Trim', en: 'EXTERIOR TRIM', items: ['FENDER GARNISH', 'DOOR GARNISH'] },
        { area: 'Interior Trim', en: 'INTERIOR TRIM', items: ['CRASH PAD', 'CONSOLE', 'DOOR TRIM', 'LUGGAGE TRIM'] },
        { area: 'HVAC System', en: 'HVAC SYSTEM', items: ['AIR DUCT', 'HVAC DUCT'] },
        { area: 'Electrical Parts', en: 'ELECTRICAL PARTS', items: ['MODULE HOUSING'] },
        { area: 'EV · Eco Parts', en: 'EV · ECO PARTS', items: ['CHARGING INLET', 'EV CHARGER HOUSING', 'HYDROGEN DOME', 'LINER COMPONENT'] },
      ],
      items: [
        { title: 'F/R BUMPER MOLD', cat: 'EXTERIOR', desc: 'Front and rear automotive bumper injection molds' },
        { title: 'CRASH PAD (I/P) MOLD', cat: 'INTERIOR', desc: 'Instrument panel injection molds for the driver console' },
        { title: 'SUNROOF PU FRAME MOLD', cat: 'EXTERIOR', desc: 'Sunroof PU frame insert injection molds' },
        { title: 'SIDE SILL GARNISH MOLD', cat: 'EXTERIOR', desc: 'Rocker (side sill) garnish injection molds' },
        { title: 'LUGGAGE SIDE TRIM MOLD', cat: 'INTERIOR', desc: 'Luggage compartment side trim injection molds' },
        { title: 'H2 LINER MOLD', cat: 'ECO', desc: 'Type 4 hydrogen storage tank liner injection molds' },
      ],
      process: ['Order &amp; Review', 'Mold Design (2D · 3D)', 'CNC Precision Machining', 'EDM · Wire-cut Machining', 'Assembly &amp; Finishing', 'Try-Out (T/O) &amp; QC', 'Delivery &amp; Production Support'],
    },
    injection: {
      title: 'Injection Production',
      subtitle: 'Injection Production',
      intro: 'Equipped with state-of-the-art injection molding machines and automated systems for stable mass production of high-quality plastic products.',
      specs: [
        { label: 'Injection Machines', value: '30 Units' },
        { label: 'Max. Clamping Force', value: '3,000ton' },
        { label: 'Monthly Capacity', value: '5M Shots' },
        { label: 'Clean Room Area', value: '300㎡' },
      ],
      items: [
        { title: 'Standard Injection', desc: 'Mass production of plastic parts from various materials' },
        { title: 'Insert Injection', desc: 'Production of composite parts with metal inserts' },
        { title: 'Double Injection', desc: 'Simultaneous molding of 2 materials/colors' },
        { title: 'High Precision', desc: 'Precision parts with ±0.01mm tolerance' },
        { title: 'Hydrogen Liner Injection', desc: 'High-pressure liner precision injection molding for hydrogen tanks' },
      ],
    },
    products: {
      title: 'Products',
      subtitle: 'Products',
      intro: 'I&TECH manufactures plastic parts for automotive interior/exterior and machinery assembly.',
      categories: ['All', 'Automotive', 'Machinery', 'Others'],
      items: [
        { name: 'Door Trim', cat: '자동차 부품', desc: 'Plastic interior door trim parts' },
        { name: 'Bumper Parts', cat: '자동차 부품', desc: 'Front/rear bumper assembly parts' },
        { name: 'Instrument Panel', cat: '자동차 부품', desc: 'Dashboard plastic structure' },
        { name: 'Console Box', cat: '자동차 부품', desc: 'Center console and storage parts' },
        { name: 'Gear Cover', cat: '기계장비용', desc: 'Industrial machinery cover parts' },
        { name: 'Housing Case', cat: '기계장비용', desc: 'Electronic component housing cases' },
        { name: 'Clips & Fasteners', cat: '기타', desc: 'Various fixing clips and fasteners' },
        { name: 'Custom Parts', cat: '기타', desc: 'Custom-order special plastic parts' },
      ],
    },
    clients: {
      title: 'Clients &amp; Coverage',
      subtitle: 'Clients &amp; Coverage',
      intro: 'I&TECH supplies injection molds and injection-molded parts to OEM automakers, Tier-1 suppliers and a range of industries — at home and abroad — anchored in the automotive parts industry. We analyze each customer\u2019s requirements and product characteristics to deliver tailor-made manufacturing and stable quality response, while continuously expanding our overseas buyer base and supply categories to broaden our reach across industries and regions. This supply experience and responsiveness is the foundation of I&TECH\u2019s trust and competitiveness.',
      statsTitle: 'Supply Track Record',
      statsSub: 'Supply Track Record',
      stats: [
        { num: '30+', label: 'Years in Business', sub: 'Years in Business' },
        { num: '4', label: 'Countries', sub: 'Countries Served' },
        { num: '15+', label: 'New Items/Yr', sub: 'New Items per Year' },
      ],
      industriesTitle: 'Industries We Serve',
      industriesSub: 'Industries',
      industries: [
        { name: 'Automotive Exterior · Interior', cat: 'AUTOMOTIVE EXT · INT', desc: 'Luggage trims, bumpers and other large automotive exterior/interior parts' },
        { name: 'Sunroof Molds', cat: 'SUNROOF MOLDS', desc: 'Standard and panoramic sunroof molds' },
        { name: 'Electronics', cat: 'ELECTRONICS', desc: 'Large-appliance housings and precision mechanism components' },
      ],
      regionsTitle: 'Sourcing Reach',
      regionsSub: 'Sourcing Reach',
      regionsDesc: 'From our Gwangju HQ, we supply molds and parts across Korea and directly export to Japan, China and India.',
      regions: [
        { code: 'KR', flag: '🇰🇷', name: 'South Korea', role: 'HQ', desc: 'Nationwide coverage: Gwangju, Jeonbuk, Hwaseong, Ulsan, Gyeongnam and more', since: '1992', primary: true },
        { code: 'JP', flag: '🇯🇵', name: 'Japan', role: 'Mold Export', desc: 'Injection molds for automotive parts suppliers', since: '2013', primary: false },
        { code: 'CN', flag: '🇨🇳', name: 'China', role: 'Mold Export', desc: 'Injection molds for automotive parts suppliers', since: '2014', primary: false },
        { code: 'IN', flag: '🇮🇳', name: 'India', role: 'Mold Export', desc: 'Injection molds for automotive parts suppliers', since: '2020', primary: false },
      ],
      globalTitle: 'Global Track Record',
      globalSub: 'Global Track Record',
      globalDesc: 'Beyond Korea, we have supplied injection molds to automotive parts makers in Japan, China, and India,\nvalidating manufacturing capability that meets OEM-level quality standards.',
      timeline: [
        { year: '2020', event: 'Started mold exports to India auto parts maker' },
        { year: '2014', event: 'Expanded mold exports to Japan &amp; China auto parts makers' },
        { year: '2013', event: 'Started mold exports to Japan auto parts maker' },
      ],
    },
    moldFacility: {
      title: 'Mold Facilities',
      subtitle: 'Mold Facilities',
      intro: 'Equipped with state-of-the-art CNC machining, precision EDM and measuring instruments for high-precision large mold manufacturing.',
      groups: [
        {
          name: 'CNC\nMachine',
          en: 'CNC MACHINE',
          specHead: 'TABLE SIZE',
          showLoad: true,
          rows: [
            { model: 'SIRIUS - 1750S', spec: '3,000 × 1,750', load: '—', qty: 1 },
            { model: 'SIRIUS - 1250S', spec: '2,150 × 850', load: '—', qty: 1 },
            { model: 'SIRIUS - 1050 8K', spec: '2,500 × 850', load: '—', qty: 1 },
            { model: 'SIRIUS - 850 S', spec: '2,150 × 850', load: '—', qty: 3 },
            { model: 'SIRIUS - 650 S', spec: '1,800 × 650', load: '—', qty: 1 },
            { model: 'SIRIUS - UL+20K', spec: '1,600 × 700', load: '—', qty: 1 },
            { model: 'SIRIUS - 7040 10K', spec: '1,600 × 700', load: '—', qty: 2 },
            { model: 'SIRIUS - 550(UL)', spec: '1,300 × 550', load: '—', qty: 2 },
          ],
        },
        {
          name: 'EDM\nMachine',
          en: 'EDM MACHINE',
          rows: [
            { model: 'UNI - 430', spec: '700 × 360', qty: 1 },
            { model: 'UNI - 500', spec: '700 × 462', qty: 1 },
            { model: 'MAKINO 106', spec: '1,300 × 950', qty: 1 },
            { model: 'MAKINO 156', spec: '2,000 × 1,000', qty: 1 },
          ],
        },
        {
          name: 'Other\nMachine',
          en: 'OTHER MACHINE',
          rows: [
            { model: 'Die Spotting Press', spec: '—', qty: '—' },
            { model: 'Mold Tilter', spec: '—', qty: '—' },
            { model: 'Hoist (Crane)', spec: '—', qty: '—' },
          ],
        },
      ],
    },
    injFacility: {
      title: 'Injection Facilities',
      subtitle: 'Injection Molding Capability',
      kicker: 'INJECTION CAPABILITY',
      hero: {
        eyebrow: '170T — 3,000T',
        headline: 'From 170T to 3,000T,\nfrom small interior parts to large exterior components',
        desc: 'I&TECH operates large-size Plant B and multi-variety Plant A together, producing the full automotive parts range — interior and exterior of all sizes — with stable mass-production capability.',
      },
      stats: [
        { v: '15', u: 'EA', l: 'Total Machines', e: 'TOTAL MACHINES' },
        { v: '3,000', u: 'T', l: 'Max Clamping Force', e: 'MAX CLAMPING' },
        { v: '2', u: 'PLT', l: 'Dedicated Plants', e: 'PLANTS' },
        { v: '24/7', u: '', l: 'Production Operation', e: 'OPERATION' },
      ],
      plantB: {
        tag: 'PLANT B · LARGE SIZE',
        title: 'Injection Plant B · Large Size',
        sub: 'Injection Plant B — Large Size',
        desc: 'Dedicated large-size molding plant for bumper and large automotive exterior components. Four large injection machines (2,100T and above) operate on automated lines in our new facility for stable large-part production.',
        machines: [
          { ton: 3000, qty: 1 },
          { ton: 2500, qty: 1 },
          { ton: 2200, qty: 1 },
          { ton: 2100, qty: 1 },
        ],
        totalLabel: '4 units',
      },
      plantA: {
        tag: 'PLANT A · MID & SMALL',
        title: 'Injection Plant A · Mid & Small Size',
        sub: 'Injection Plant A — Mid & Small Size',
        desc: 'A multi-variety production line for mid- and small-size automotive parts. Machines ranging from 180T to 2,200T provide flexible response to a wide range of part specifications.',
        machines: [
          { ton: 2200, qty: 1 },
          { ton: 2000, qty: 1 },
          { ton: 1400, qty: 1 },
          { ton: 1300, qty: 1 },
          { ton: 850, qty: 1 },
          { ton: 650, qty: 1 },
          { ton: 550, qty: 2 },
          { ton: 380, qty: 1 },
          { ton: 300, qty: 1 },
          { ton: 180, qty: 1 },
        ],
        totalLabel: '11 units',
      },
      capability: {
        tag: 'PRODUCTION CAPABILITY',
        title: 'Automotive Parts Mass-Production Capability',
        desc: 'Beyond owning machines, we operate a production system that covers the entire automotive parts range.',
        items: [
          { ko: 'Automotive Interior Parts', en: 'Automotive Interior Parts' },
          { ko: 'Automotive Exterior Parts', en: 'Automotive Exterior Parts' },
          { ko: 'Large-size Bumper Molding', en: 'Large-size Bumper Molding' },
          { ko: 'Sunroof Components', en: 'Sunroof Components' },
          { ko: 'Luggage Trim', en: 'Luggage Trim' },
          { ko: 'Insert Molding', en: 'Insert Molding' },
          { ko: 'Mass Production System', en: 'Mass Production System' },
        ],
      },
    },
    factory: {
      title: 'Factory Gallery',
      subtitle: 'Factory Gallery',
      intro: 'Explore I&TECH\'s latest production facilities and factory interior.',
      areas: ['Mold Shop', 'Injection Shop', 'Quality Lab', 'R&D Center'],
    },
    quality: {
      title: 'Quality Management System',
      subtitle: 'Quality Management System',
      intro: 'Backed by SQ Mark top-grade certification, I&TECH manages every stage — from mold fabrication and injection production to inspection and shipment — in-house under a unified process. Accumulated expertise and standardized workflows let us meet both the quality bar and the delivery schedule our customers demand.',
      sqTitle: 'SQ Mark — Top Grade',
      sqDesc: 'I&TECH holds the highest grade in both Injection and Injection Mold divisions of the Hyundai · Kia SQ certification system — a comprehensive assessment of suppliers across quality, delivery and technology. An A-grade signals OEM direct-delivery class reliability.',
      pillars: [
        { num: '01', title: 'Quality Response', sub: 'Quality Response',
          items: ['Operating to SQ Mark top-grade standards', 'Compliance with customer quality criteria', 'Mass-production quality process'] },
        { num: '02', title: 'Production Control', sub: 'Production Control',
          items: ['Integrated mold-to-injection control', 'Process-level quality checks', 'Production history & traceability'] },
        { num: '03', title: 'Inspection System', sub: 'Inspection System',
          items: ['First-article inspection', 'In-process inspection', 'Outgoing inspection'] },
        { num: '04', title: 'Customer Response', sub: 'Customer Response',
          items: ['Customer requirements integration', 'Rapid issue response', 'Continuous quality improvement'] },
      ],
      flowTitle: 'Quality Control Flow',
      flowSub: 'From receiving to shipment, each stage is verified to guarantee quality.',
      flow: [
        ['Incoming', 'Raw materials & parts'],
        ['First Article', 'Initial-run approval'],
        ['In-Process', 'Self-check during injection'],
        ['Final', 'Dimension · Visual · Function'],
        ['Outgoing', 'Packaging & identification'],
      ],
      galleryTitle: 'Quality Control on the Floor',
      gallery: [
        { label: 'Quality Meeting', desc: 'Weekly quality review & improvement' },
        { label: 'Metrology Lab', desc: 'CMM precision measurement room' },
        { label: 'Inspection Equipment', desc: '3D scanners · gauges' },
        { label: 'Injection Shop Floor', desc: 'Real-time quality monitoring' },
      ],
    },
    esg: {
      title: 'ESG Management',
      subtitle: 'ESG Management',
      intro: 'I&TECH realizes sustainable management centered on three pillars: Environment (E), Social (S), and Governance (G).',
      certTitle: 'Certifications',
      certDesc: 'I&TECH has established a management system that meets international standards, responding to the trust of customers and society.',
      certs: [
        { code: 'ISO 9001:2015', name: 'Quality Management System', body: 'KFQ Korea', year: '2024', scope: 'Mold design, manufacturing & injection molding', color: '#0d2045', desc: 'International standard ensuring consistent product quality and customer satisfaction.', img: 'uploads/HGtk6cFbQAASlCV-b8246150.jpeg' },
        { code: 'ISO 14001:2015', name: 'Environmental Management', body: 'KFQ Korea', year: '2023', scope: 'Environmental impact across all processes', color: '#2e7d52', desc: 'International certification for systematic environmental management and continuous improvement.', img: null },
        { code: 'ISO 45001:2018', name: 'Occupational Health & Safety', body: 'KSA Korea', year: '2023', scope: 'Employee safety across all facilities', color: '#8b2500', desc: 'The highest-level international certification for employee safety and health management.', img: null },
        { code: 'IATF 16949', name: 'Automotive Quality Management', body: 'Bureau Veritas', year: '2023', scope: 'Injection mold & plastic parts for automotive', color: '#1a56a0', desc: 'The highest-level automotive quality certification required by Hyundai, Kia and global OEMs.', img: null },
      ],
      pillars: [
        {
          key: 'E', label: 'Environmental', color: '#2e7d52',
          items: ['Setting and implementing GHG emission reduction targets', 'Improving energy efficiency and introducing renewables', 'Increasing waste recycling rates', 'Prioritizing eco-friendly raw materials'],
        },
        {
          key: 'S', label: 'Social', color: '#1a56a0',
          items: ['Strengthening employee safety and health management', 'Fair hiring and respect for diversity', 'Mutual cooperation with partner companies', 'Participation in local community contribution activities'],
        },
        {
          key: 'G', label: 'Governance', color: '#5a3a8c',
          items: ['Transparent disclosure of management information', 'Practicing ethical management and anti-corruption', 'Strengthening board independence', 'Enhanced communication with shareholders and stakeholders'],
        },
      ],
    },
    contact: {
      title: 'Contact Us',
      subtitle: 'Contact Us',
      intro: 'Please leave your inquiry and we will respond as soon as possible.',
      fields: { name: 'Name', company: 'Company', tel: 'Phone', email: 'Email', subject: 'Subject', message: 'Message', agree: 'I agree to the collection and use of personal information.', submit: 'Submit Inquiry', required: 'Please fill in all required fields.', success: 'Your inquiry has been received. We will respond shortly.' },
      info: { addr: '23, 31, Cheomdanyeonsin-ro 398beon-gil, Buk-gu, Gwangju, Korea', tel: '062-959-9100', fax: '062-954-5332', email: 'info@it9100.co.kr', hours: 'Mon–Fri 09:00–18:00 (Closed weekends & holidays)' },
    },
    footer: {
      company: 'I&TECH Co., Ltd.',
      biz: 'Business Reg. No: 410-81-69700',
      addr: '23, 31, Cheomdanyeonsin-ro 398beon-gil, Buk-gu, Gwangju, Korea',
      tel: 'TEL: 062-959-9100',
      fax: 'FAX: 062-954-5332',
      email: 'EMAIL: info@it9100.co.kr',
      copy: '© 2024 I&TECH Co., Ltd. All Rights Reserved.',
      privacy: 'Privacy Policy',
    },
  },
};
